swagger: "2.0"
info:
  version: "0.0.1"
  title: "URL Shortener"
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  - http
  - https
produces:
  - application/json
paths:
  /generate-url:
    x-swagger-router-controller: generate-url
    post:
      description: Generates a short URL that will redirect to the given one
      operationId: generate
      parameters:
        - name: url
          in: query
          description: The URL to be shortened
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenerateURLResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /add-custom-url:
    x-swagger-router-controller: add-custom-url
    post:
      description: Stores a custom URL to redirect to
      operationId: addCustomURL
      parameters:
        - name: url
          in: query
          description: The URL to be shortened
          required: true
          type: string
        - name: customPath
          in: query
          description: The custom path for the new URL
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GenerateURLResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /stats:
    x-swagger-router-controller: stats
    get:
      description: Get stats for a given path
      operationId: stats
      parameters:
        - name: path
          in: query
          description: The path to get stats for
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/StatsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /go/{path}:
    x-swagger-router-controller: redirect
    get:
      description: Redirects to the URL stored for the given path
      operationId: redirect
      parameters:
        - name: path
          in: path
          description: The short path mapped to a url
          required: true
          type: string
      responses:
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  GenerateURLResponse:
    required:
      - shortURL
    properties:
      shortURL:
        type: string
  StatsResponse:
    required:
      - createdDate
      - totalViews
      - viewsPerDay
    properties:
      createdDate:
        type: string
      totalViews:
        type: integer
      viewsPerDay:
        type: object
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
